# The objective is to perform VSTESTV2 with default values

jobs:
- job: Windows
  displayName: 'Run Tests'
  pool:
    vmImage: 'windows-2019'
  steps:              
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'SpecificVersion'  
      testPlatformVersion: '16.8.0-preview-20200921-01'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*Test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\'
      vsTestVersion: 'toolsInstaller'
      codeCoverageEnabled: true
      distributionBatchType: 'basedOnTestCases'
      batchingBasedOnAgentsOption: 'customBatchSize'
      customBatchSizeValue: '1'
      

