# The objective is to perform VSTESTV2 with default values

jobs:
- job: Windows
  displayName: 'Run Tests'
  pool:
    vmImage: 'windows-2019'
  

  steps:              
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestStable'  

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*Test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\'
      vsTestVersion: 'toolsInstaller'
      codeCoverageEnabled: true
  
      

